/**
 * AUTO-GENERATED.
 * DO NOT EDIT.
 *
 * Generated by:
 * scripts/build-content.js
 */
export const generatedContent = {
  "index": {
    "version": 1,
    "contentVersion": 1,
    "generatedAt": "2026-09-03T01:21:00.375Z",
    "generator": "scripts/build-content.js",
    "regularLessons": [
      "lesson-append-and-open-lines",
      "lesson-basic-movement",
      "lesson-change-inner-word-ciw",
      "lesson-change-word-cw",
      "lesson-counts-move-faster",
      "lesson-delete-basics",
      "lesson-delete-end-replace",
      "lesson-delete-inner-word-diw",
      "lesson-how-to-exit-ex-commands",
      "lesson-insert-mode",
      "lesson-line-bounds-0-and",
      "lesson-line-jumps",
      "lesson-search-backward",
      "lesson-search-forward",
      "lesson-search-navigation-n-n",
      "lesson-undo-redo",
      "lesson-word-movement",
      "lesson-yank-put-copy-paste"
    ],
    "practiceLessons": [
      "lesson-practice-backward-search-practice",
      "lesson-practice-basic-movement-practice",
      "lesson-practice-change-word-practice",
      "lesson-practice-delete-character-practice",
      "lesson-practice-delete-line-practice",
      "lesson-practice-delete-to-end-practice",
      "lesson-practice-delete-word-practice",
      "lesson-practice-ex-commands-practice",
      "lesson-practice-forward-search-practice",
      "lesson-practice-insert-mode-practice",
      "lesson-practice-line-boundary-practice",
      "lesson-practice-line-jump-practice",
      "lesson-practice-replace-character-practice",
      "lesson-practice-search-navigation-practice",
      "lesson-practice-undo-redo-practice",
      "lesson-practice-word-motion-practice",
      "lesson-practice-yank-and-paste-practice"
    ]
  },
  "lessons": {
    "lesson-append-and-open-lines": {
      "id": "lesson-append-and-open-lines",
      "version": 1,
      "name": "Append and Open Lines",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "a でカーソルの後ろに文字を追加します。o で下に新しい行を開き、O で上に新しい行を開きます。2つの行の間に新しい行を追加し、「Inserted here」と入力してください。",
      "initialContent": [
        "First line.",
        "Second line."
      ],
      "targetContent": [
        "First line.",
        "Inserted here",
        "Second line."
      ],
      "focusCommand": "a"
    },
    "lesson-basic-movement": {
      "id": "lesson-basic-movement",
      "version": 1,
      "name": "基本移動",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "h、j、k、l を使ってカーソルを移動し、目標の文字「$」まで到達してください。",
      "initialContent": [
        "Move with h(left), j(down), k(up), l(right).",
        "Your cursor starts here.",
        "",
        "The goal is to navigate to the dollar sign.",
        "Practice moving around the text.",
        "Once you are comfortable, move to the '$'."
      ],
      "target": {
        "row": 5,
        "col": 39
      },
      "focusCommand": "hjkl"
    },
    "lesson-change-inner-word-ciw": {
      "id": "lesson-change-inner-word-ciw",
      "version": 1,
      "name": "Change Inner Word (ciw)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-10",
        "difficulty": "intermediate",
        "tags": [
          "normal",
          "editing",
          "text-object"
        ],
        "estimatedTime": 45,
        "prerequisites": [
          "lesson-delete-inner-word-diw"
        ],
        "learningObjectives": [
          "Use 'ciw' to change a word completely without needing to be at its start",
          "Understand how 'c' combines with 'iw'"
        ]
      },
      "instructions": "ciw を使って、単語内のどこにカーソルがあっても「wrong」を「right」に変更してください。終わったら Esc を押します。",
      "initialContent": [
        "This is the wrong word."
      ],
      "initialCursor": {
        "row": 0,
        "col": 14
      },
      "targetContent": [
        "This is the right word."
      ],
      "solution": [
        "c",
        "i",
        "w",
        "r",
        "i",
        "g",
        "h",
        "t",
        "Escape"
      ],
      "focusCommand": "ciw"
    },
    "lesson-change-word-cw": {
      "id": "lesson-change-word-cw",
      "version": 1,
      "name": "Change Word (cw)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "cw を使って「bad」を「good」に変更してください。終わったら Esc を押します。",
      "initialContent": [
        "This is a bad example."
      ],
      "targetText": {
        "line": 0,
        "text": "This is a good example."
      },
      "focusCommand": "VIM"
    },
    "lesson-counts-move-faster": {
      "id": "lesson-counts-move-faster",
      "version": 1,
      "name": "Counts: Move Faster",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "移動コマンドに回数を指定します。3 を押してから w を押し、3単語先の「target」まで移動してください。",
      "initialContent": [
        "one two three target here"
      ],
      "target": {
        "row": 0,
        "col": 14
      },
      "focusCommand": "VIM"
    },
    "lesson-delete-basics": {
      "id": "lesson-delete-basics",
      "version": 1,
      "name": "Delete Basics",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "dd を使って中央の行全体を削除します。次に dw を使って最終行の「mistake」を削除してください。必要なら x で1文字だけ削除できます。",
      "initialContent": [
        "Keep this line.",
        "Delete this entire line.",
        "Fix this mistake here."
      ],
      "targetContent": [
        "Keep this line.",
        "Fix this here."
      ],
      "focusCommand": "x"
    },
    "lesson-delete-end-replace": {
      "id": "lesson-delete-end-replace",
      "version": 1,
      "name": "Delete End & Replace",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "D を使ってカーソル位置から行末まで削除し、そのあと r を使って「x」を「!」に置き換えてください。",
      "initialContent": [
        "Keep this → remove from here to end",
        "Replace this x"
      ],
      "targetContent": [
        "Keep this → ",
        "Replace this !"
      ],
      "focusCommand": "D"
    },
    "lesson-delete-inner-word-diw": {
      "id": "lesson-delete-inner-word-diw",
      "version": 1,
      "name": "Delete Inner Word (diw)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-10",
        "difficulty": "intermediate",
        "tags": [
          "normal",
          "deletion",
          "text-object"
        ],
        "estimatedTime": 45,
        "prerequisites": [
          "lesson-delete-basics"
        ],
        "learningObjectives": [
          "Understand the 'iw' (inner word) text object",
          "Use 'diw' to delete a word without needing to be at its start"
        ]
      },
      "instructions": "diw を使って、単語内のどこにカーソルがあっても「mistake」を削除してください。",
      "initialContent": [
        "This mistake is annoying."
      ],
      "initialCursor": {
        "row": 0,
        "col": 8
      },
      "targetContent": [
        "This  is annoying."
      ],
      "solution": [
        "d",
        "i",
        "w"
      ],
      "focusCommand": "diw"
    },
    "lesson-how-to-exit-ex-commands": {
      "id": "lesson-how-to-exit-ex-commands",
      "version": 1,
      "name": "How to Exit (Ex Commands)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": ":q で終了、または :wq で保存して終了します。コマンドを入力したら Enter を押してください。",
      "initialContent": [
        "Welcome to VIM Master!",
        "Most searched question: how to exit Vim?",
        "Try typing :q and press Enter (or :wq)."
      ],
      "exCommands": [
        "q",
        "wq"
      ],
      "focusCommand": ":q"
    },
    "lesson-insert-mode": {
      "id": "lesson-insert-mode",
      "version": 1,
      "name": "Insert Mode",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "a を押してカーソルの後ろに追加します。「 is awesome!」と入力し、Esc を押して NORMAL モードに戻ってください。",
      "initialContent": [
        "VIM has multiple modes. You've been in NORMAL mode.",
        "Press 'a' to append after the cursor and start typing.",
        "When you're done, press 'Escape' to go back.",
        "Your task: complete the sentence below.",
        "Learning VIM"
      ],
      "targetText": {
        "line": 4,
        "text": "Learning VIM is awesome!"
      },
      "focusCommand": "i"
    },
    "lesson-line-bounds-0-and": {
      "id": "lesson-line-bounds-0-and",
      "version": 1,
      "name": "Line Bounds (0 and $)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "0 で行頭へ、$ で行末へ移動します。1行目の最後の文字まで移動してください。",
      "initialContent": [
        "Jump to the start and end of this line.",
        "Practice makes perfect."
      ],
      "target": {
        "row": 0,
        "col": 38
      },
      "focusCommand": "0 / $"
    },
    "lesson-line-jumps": {
      "id": "lesson-line-jumps",
      "version": 1,
      "name": "Line Jumps",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "gg で先頭行へ、G で最終行へ移動します。最終行の最後の文字まで移動してください。",
      "initialContent": [
        "This is the first line. Use 'gg' to come here.",
        "...",
        "...",
        "...",
        "This is the last line. Use 'G' to jump here.",
        "The target is on the word 'here'."
      ],
      "target": {
        "row": 5,
        "col": 30
      },
      "focusCommand": "gg / G"
    },
    "lesson-practice-backward-search-practice": {
      "id": "lesson-practice-backward-search-practice",
      "version": 1,
      "name": "Backward Search Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "search-backward"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "?text で後方検索し、N で前の一致へ移動します。「start」を後方検索してください。",
      "initialContent": [
        "Search backward for 'start' in this text.",
        "Use ?start and press Enter to search backward.",
        "Then use 'N' to find the previous occurrence.",
        "Navigate to the start word.",
        "The start is here: start",
        "Another start appears earlier: start"
      ],
      "target": {
        "row": 4,
        "col": 20
      },
      "focusCommand": "VIM"
    },
    "lesson-practice-basic-movement-practice": {
      "id": "lesson-practice-basic-movement-practice",
      "version": 1,
      "name": "Basic Movement Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "hjkl"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "h、j、k、l を使ってカーソルを移動し、目標の文字「$」まで移動してください。",
      "initialContent": [
        "Practice basic movement with h(left), j(down), k(up), l(right).",
        "Your cursor starts here.",
        "",
        "The goal is to navigate to the dollar sign below.",
        "Practice moving around the text first.",
        "Once comfortable, move to the '$' target.",
        "Target: $"
      ],
      "target": {
        "row": 6,
        "col": 8
      },
      "focusCommand": "hjkl"
    },
    "lesson-practice-change-word-practice": {
      "id": "lesson-practice-change-word-practice",
      "version": 1,
      "name": "Change Word Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "cw"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "cw を使って単語を変更します。間違っている単語を正しい単語に置き換えてください。",
      "initialContent": [
        "The wrong animal is a elephant",
        "I like to eat wrong food",
        "VIM is a wrong editor",
        "Programming is wrong activity"
      ],
      "targetContent": [
        "The best animal is a elephant",
        "I like to eat good food",
        "VIM is a great editor",
        "Programming is fun activity"
      ],
      "focusCommand": "VIM"
    },
    "lesson-practice-delete-character-practice": {
      "id": "lesson-practice-delete-character-practice",
      "version": 1,
      "name": "Delete Character Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "x"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "x を使って文字を削除します。「Delete X this」から X を削除し、ほかのタイプミスも修正してください。",
      "initialContent": [
        "Delete the X from this line: 'Delete X this'",
        "Use x to remove the X character",
        "Also fix: 'Fixx this typo'",
        "And: 'Removve extra letters'"
      ],
      "targetContent": [
        "Delete the  this",
        "Use x to remove the  character",
        "Also fix: 'Fix this typo'",
        "And: 'Remove extra letters'"
      ],
      "focusCommand": "VIM"
    },
    "lesson-practice-delete-line-practice": {
      "id": "lesson-practice-delete-line-practice",
      "version": 1,
      "name": "Delete Line Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "dd"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "dd を使って行全体を削除します。印の付いた行を削除してください。",
      "initialContent": [
        "Keep this line",
        "DELETE THIS LINE",
        "Keep this line too",
        "REMOVE THIS ONE TOO",
        "Keep this final line"
      ],
      "targetContent": [
        "Keep this line",
        "Keep this line too",
        "Keep this final line"
      ],
      "focusCommand": "VIM"
    },
    "lesson-practice-delete-to-end-practice": {
      "id": "lesson-practice-delete-to-end-practice",
      "version": 1,
      "name": "Delete to End Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "D"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "D を使ってカーソル位置から行末まで削除します。不要な行末部分を削除してください。",
      "initialContent": [
        "Keep this part DELETE_FROM_HERE_TO_END",
        "Preserve this DELETE_REST_OF_LINE",
        "Save this text REMOVE_EVERYTHING_AFTER",
        "Maintain this DELETE_TO_FINISH"
      ],
      "targetContent": [
        "Keep this part",
        "Preserve this",
        "Save this text",
        "Maintain this"
      ],
      "focusCommand": "VIM"
    },
    "lesson-practice-delete-word-practice": {
      "id": "lesson-practice-delete-word-practice",
      "version": 1,
      "name": "Delete Word Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "dw"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "dw を使って単語を削除します。余分な単語を削除して文章を整えてください。",
      "initialContent": [
        "This is a very very long sentence with extra words.",
        "Remove unnecessary extra words from this line too.",
        "Delete unwanted unwanted repetitions here.",
        "Clean up this messy messy text.",
        "Final result should be clean sentences."
      ],
      "targetContent": [
        "This is a very long sentence with words.",
        "Remove unnecessary words from this line too.",
        "Delete unwanted repetitions here.",
        "Clean up this messy text.",
        "Final result should be clean sentences."
      ],
      "focusCommand": "VIM"
    },
    "lesson-practice-ex-commands-practice": {
      "id": "lesson-practice-ex-commands-practice",
      "version": 1,
      "name": "Ex Commands Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "ex"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": ":q で終了、:wq で保存して終了するなどのExコマンドを練習します。:q と入力して Enter を押してください。",
      "initialContent": [
        "This is a VIM lesson for ex-commands",
        "Ex-commands start with a colon (:)",
        "Common commands: :q (quit), :w (write), :wq (write and quit)",
        "Type :q and press Enter to complete this lesson"
      ],
      "targetText": {
        "line": 3,
        "text": "Type :q and press Enter to complete this lesson"
      },
      "focusCommand": "VIM"
    },
    "lesson-practice-forward-search-practice": {
      "id": "lesson-practice-forward-search-practice",
      "version": 1,
      "name": "Forward Search Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "search-forward"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "/text で前方検索し、n で次の一致へ進みます。「target」を検索して、その位置まで移動してください。",
      "initialContent": [
        "Search for the word 'target' in this text.",
        "Use /target and press Enter to search.",
        "Then use 'n' to find the next occurrence.",
        "Navigate to the target word.",
        "The target is here: target",
        "Another target appears later: target"
      ],
      "target": {
        "row": 4,
        "col": 20
      },
      "focusCommand": "VIM"
    },
    "lesson-practice-insert-mode-practice": {
      "id": "lesson-practice-insert-mode-practice",
      "version": 1,
      "name": "Insert Mode Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "ia"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "i でカーソルの前に挿入し、a でカーソルの後ろに追加します。「INSERTED」と「APPENDED」を入力してください。",
      "initialContent": [
        "VIM has multiple modes. You're in NORMAL mode now.",
        "Press 'i' to insert before cursor and type 'INSERTED'.",
        "Press 'a' to append after cursor and type 'APPENDED'.",
        "When done, press 'Escape' to return to NORMAL mode.",
        "Complete the sentence: Learning VIM"
      ],
      "targetText": {
        "line": 4,
        "text": "Learning VIM INSERTED APPENDED"
      },
      "focusCommand": "i"
    },
    "lesson-practice-line-boundary-practice": {
      "id": "lesson-practice-line-boundary-practice",
      "version": 1,
      "name": "Line Boundary Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "0$"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "0 で行頭へ、$ で行末へ移動します。行頭と行末の間を移動する練習をしてください。",
      "initialContent": [
        "Start here and go to end with $",
        "Then return to start with 0",
        "Practice moving between line boundaries",
        "Use 0 for start, $ for end of each line"
      ],
      "target": {
        "row": 0,
        "col": 0
      },
      "focusCommand": "VIM"
    },
    "lesson-practice-line-jump-practice": {
      "id": "lesson-practice-line-jump-practice",
      "version": 1,
      "name": "Line Jump Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "ggG"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "gg で先頭行へ、G で最終行へ移動します。最終行の最後の文字まで移動してください。",
      "initialContent": [
        "This is the first line. Use 'gg' to come here.",
        "Second line",
        "Third line",
        "Fourth line",
        "This is the last line. Use 'G' to jump here.",
        "The target is the last character of this line."
      ],
      "target": {
        "row": 5,
        "col": 30
      },
      "focusCommand": "VIM"
    },
    "lesson-practice-replace-character-practice": {
      "id": "lesson-practice-replace-character-practice",
      "version": 1,
      "name": "Replace Character Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "r"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "r を使って1文字を置き換えます。間違っている文字を置き換えてタイプミスを修正してください。",
      "initialContent": [
        "Thxs is a test",
        "VxM is awesome",
        "Reylace characters",
        "Fxx typos quickly"
      ],
      "targetContent": [
        "This is a test",
        "VIM is awesome",
        "Replace characters",
        "Fix typos quickly"
      ],
      "focusCommand": "VIM"
    },
    "lesson-practice-search-navigation-practice": {
      "id": "lesson-practice-search-navigation-practice",
      "version": 1,
      "name": "Search Navigation Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "nN"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "最初に「word」を検索し、n で次の一致、N で前の一致へ移動します。3番目の出現位置まで移動してください。",
      "initialContent": [
        "Find the word in this text",
        "Another word appears here",
        "The third word is the target",
        "More word instances follow",
        "Final word at the end"
      ],
      "target": {
        "row": 2,
        "col": 10
      },
      "focusCommand": "n"
    },
    "lesson-practice-undo-redo-practice": {
      "id": "lesson-practice-undo-redo-practice",
      "version": 1,
      "name": "Undo Redo Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "undo-redo"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "何か変更したあと、u で元に戻し、Ctrl+r でやり直します。Undo／Redo の操作を練習してください。",
      "initialContent": [
        "Original text that will be modified",
        "Change this line and then undo it",
        "Practice undoing and redoing changes",
        "Master the undo/redo workflow"
      ],
      "target": {
        "row": 0,
        "col": 0
      },
      "focusCommand": "u"
    },
    "lesson-practice-word-motion-practice": {
      "id": "lesson-practice-word-motion-practice",
      "version": 1,
      "name": "Word Motion Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "wbe"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "w（次の単語）、b（前の単語）、e（単語の末尾）を使います。「destination」という単語の末尾まで移動してください。",
      "initialContent": [
        "Jumping between words is much faster than character by character.",
        "Use 'w' to jump forwards to the start of the next word.",
        "Use 'b' to jump backwards to the start of the previous word.",
        "Use 'e' to jump to the end of the current word.",
        "Find the ultimate destination."
      ],
      "target": {
        "row": 4,
        "col": 28
      },
      "focusCommand": "VIM"
    },
    "lesson-practice-yank-and-paste-practice": {
      "id": "lesson-practice-yank-and-paste-practice",
      "version": 1,
      "name": "Yank and Paste Practice",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "practice",
          "yyp"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "yy で行をヤンク（コピー）し、p で貼り付けます。重要な行を複製してください。",
      "initialContent": [
        "This line should be duplicated",
        "",
        "This line should also be duplicated",
        "",
        "Don't duplicate this line"
      ],
      "targetContent": [
        "This line should be duplicated",
        "This line should be duplicated",
        "",
        "This line should also be duplicated",
        "This line should also be duplicated",
        "",
        "Don't duplicate this line"
      ],
      "focusCommand": "VIM"
    },
    "lesson-search-backward": {
      "id": "lesson-search-backward",
      "version": 1,
      "name": "Search Backward (?)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "? を押して「alpha」と入力し Enter を押します。そのあと N を1回押して前の一致へ移動してください。",
      "initialContent": [
        "alpha beta gamma",
        "delta epsilon alpha",
        "zeta eta theta"
      ],
      "target": {
        "row": 0,
        "col": 0
      },
      "focusCommand": "?"
    },
    "lesson-search-forward": {
      "id": "lesson-search-forward",
      "version": 1,
      "name": "Search Forward (/)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "/ を押して「target」と入力し Enter を押します。そのあと n を1回押して次の一致へ移動してください。",
      "initialContent": [
        "find the target here",
        "another target and another target",
        "no match on this line"
      ],
      "target": {
        "row": 1,
        "col": 27
      },
      "focusCommand": "/"
    },
    "lesson-search-navigation-n-n": {
      "id": "lesson-search-navigation-n-n",
      "version": 1,
      "name": "Search Navigation (n/N)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "/foo で「foo」を検索し、そのあと n を2回押して3番目の出現位置まで移動してください。",
      "initialContent": [
        "foo bar baz",
        "qux foo quux",
        "corge grault foo"
      ],
      "target": {
        "row": 2,
        "col": 13
      },
      "focusCommand": "n"
    },
    "lesson-undo-redo": {
      "id": "lesson-undo-redo",
      "version": 1,
      "name": "Undo / Redo",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "中央の行を dd で削除し、u で元に戻したあと、Ctrl+r でやり直してください。最後は中央の行が削除された状態にします。",
      "initialContent": [
        "Top line.",
        "Remove me.",
        "Bottom line."
      ],
      "targetContent": [
        "Top line.",
        "Bottom line."
      ],
      "focusCommand": "u"
    },
    "lesson-word-movement": {
      "id": "lesson-word-movement",
      "version": 1,
      "name": "Word Movement",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "w（次の単語）、b（前の単語）、e（単語の末尾）を使います。「destination」という単語の末尾まで移動してください。",
      "initialContent": [
        "Jumping between words is much faster.",
        "Use 'w' to jump forwards to the start of the next word.",
        "Use 'b' to jump backwards to the start of the previous word.",
        "Use 'e' to jump to the end of the current word.",
        "Find the ultimate destination."
      ],
      "target": {
        "row": 4,
        "col": 28
      },
      "focusCommand": "w"
    },
    "lesson-yank-put-copy-paste": {
      "id": "lesson-yank-put-copy-paste",
      "version": 1,
      "name": "Yank & Put (Copy/Paste)",
      "metadata": {
        "revision": 1,
        "author": "VIM Master Team",
        "githubUsername": "vimmaster",
        "created": "2026-07-09",
        "difficulty": "beginner",
        "tags": [
          "normal"
        ],
        "estimatedTime": 60,
        "prerequisites": [],
        "learningObjectives": []
      },
      "instructions": "yy で行をヤンク（コピー）し、p でプット（貼り付け）します。2行目を複製してください。",
      "initialContent": [
        "Let's copy and paste.",
        "Yank this line!",
        "And put it below this line.",
        ""
      ],
      "targetContent": [
        "Let's copy and paste.",
        "Yank this line!",
        "And put it below this line.",
        "Yank this line!"
      ],
      "focusCommand": "p"
    }
  }
};
